### ISSUE TITLE
Bug Report: error 404 page when leaving the credits

### ISSUE THREAD

**Issue by Trippy-animates** [DragginGroup/Blog#4]
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What browser are you using?

Opera

### Version

0.2.0

### Context (Provide images, videos, etc.)

So basically, if you exit the credits page there will be an error 404 page that says "File not found".

### Steps to reproduce (or crash logs, errors, etc.)

Start your computer, open your browser, open the site, go to the credits page, click on the leave button, voilà
![image](https://github.com/user-attachments/assets/c964836c-62f2-449d-9c27-62292d6cdabe)

**Comment by PortilizenDev** [comment]
In 0.2.1 I am planning to reprogram most of the fuckin pages and shit cause they didn't fuckin work so this issue will be gone soon or later.

**Comment by PortilizenDev** [comment]
V0.2.1 fixes thia issue
